export const FLUENT_EMOJI_MAPPING: Record<string, string> = {
  'Sun': 'Sun',
  'Cloud': 'Cloud',
  'Flower': 'Cherry blossom',
  'Tree': 'Deciduous tree',
  'Book': 'Open book',
  'Water': 'Droplet',
  'Milk': 'Glass of milk',
  'Apple': 'Red apple',
  'Ball': 'Soccer ball',
  'Car': 'Automobile',
  'Plane': 'Airplane',
  'Train': 'Locomotive',
  'Fish': 'Fish',
  'Dog': 'Dog face',
  'Cat': 'Cat face',
  'Star': 'Star',
  'Moon': 'Crescent moon',
  'Gift': 'Wrapped gift',
  'Party': 'Party popper',
  'Crown': 'Crown',
  'Sword': 'Sword',
  'Shield': 'Shield',
  'Rainbow': 'Rainbow',
  'Arrow': 'Left arrow',
  'Clock': 'Alarm clock',
  'Lamp': 'Light bulb',
  'House': 'House',
  'Smartphone': 'Mobile phone',
  'Monitor': 'Desktop computer',
  'Camera': 'Camera',
  'Music': 'Musical note',
  'Heart': 'Red heart',
  'Smile': 'Grinning face with smiling eyes',
  'Coffee': 'Hot beverage',
  'Pizza': 'Pizza',
  'Cake': 'Shortcake',
  'Cookie': 'Cookie',
  'Shirt': 'T-shirt',
  'Glasses': 'Glasses',
  'Bag': 'Backpack',
  'Key': 'Key',
  'Umbrella': 'Umbrella',
  'Mountain': 'Mountain',
  'Sea': 'Water wave',
  'Leaf': 'Leaf fluttering in wind',
  'Fire': 'Fire',
  'Wind': 'Wind face',
  'Lightning': 'High voltage',
  'Snow': 'Snowflake',
  'Ghost': 'Ghost',
  'Rocket': 'Rocket',
  'Bike': 'Bicycle',
  'Anchor': 'Anchor',
  'Bell': 'Bell',
  'Bird': 'Bird',
  'Bone': 'Bone',
  'Bug': 'Lady beetle',
  'Bus': 'Bus',
  'Cherry': 'Cherries',
  'Rain': 'Cloud with rain',
  'Compass': 'Compass',
  'Chip': 'Processor',
  'Diamond': 'Gem stone',
  'Dice': 'Game die',
  'Drum': 'Drum',
  'Egg': 'Egg',
  'Eye': 'Eye',
  'Feather': 'Feather',
  'Footprints': 'Footprints',
  'Hammer': 'Hammer',
  'Hand': 'Raised hand',
  'Headphones': 'Headphones',
  'Question': 'Help',
  'Time': 'Hourglass done',
  'Infinity': 'Infinity',
  'Laptop': 'Laptop',
  'Bulb': 'Light bulb',
  'Lock': 'Locked',
  'Magnet': 'Magnet',
  'Mail': 'Envelope',
  'Map': 'World map',
  'Pin': 'Round pushpin',
  'Mic': 'Microphone',
  'Microscope': 'Microscope',
  'Mouse': 'Computer mouse',
  'Palette': 'Artist palette',
  'Paperclip': 'Paperclip',
  'Pen': 'Pen',
  'Phone': 'Telephone receiver',
  'Piano': 'Musical keyboard',
  'Pill': 'Pill',
  'Landing': 'Airplane landing',
  'Takeoff': 'Airplane departure',
  'Plug': 'Electric plug',
  'Printer': 'Printer',
  'Puzzle': 'Puzzle piece',
  'Radio': 'Radio',
  'Recycle': 'Recycling symbol',
  'Scissors': 'Scissors',
  'Search': 'Magnifying glass tilted left',
  'Settings': 'Gear',
  'Shell': 'Spiral shell',
  'Shopping Bag': 'Shopping bags',
  'Cart': 'Shopping cart',
  'Shovel': 'Shovel',
  'Speaker': 'Loudspeaker',
  'Sprout': 'Seedling',
  'Stamp': 'Postbox',
  'Stethoscope': 'Stethoscope',
  'Target': 'Bullseye',
  'Telescope': 'Telescope',
  'Tent': 'Tent',
  'Thermometer': 'Thermometer',
  'Ticket': 'Ticket',
  'Trash': 'Wastebasket',
  'Trophy': 'Trophy',
  'Truck': 'Delivery truck',
  'TV': 'Television',
  'Fork': 'Fork and knife',
  'Video': 'Video camera',
  'Volume': 'Speaker high volume',
  'Wallet': 'Wallet',
  'Wand': 'Magic wand',
  'Wine': 'Wine glass',
  'Tool': 'Wrench'
};

export function getFluentEmojiUrl(label: string): string | null {
  const emojiName = FLUENT_EMOJI_MAPPING[label];
  if (!emojiName) return null;

  // Format: https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji@latest/assets/<Emoji Name>/3D/<emoji_name_lower_with_underscores>_3d.png
  const folderName = encodeURIComponent(emojiName);
  const fileName = emojiName.toLowerCase().replace(/ /g, '_');
  
  return `https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji@latest/assets/${folderName}/3D/${fileName}_3d.png`;
}
