import { 
  Sun, Cloud, Flower, Rose, Trees, Book, Library, Droplet, Milk, Apple, 
  Banana, Citrus, Carrot, Grape, Soup, IceCreamCone,
  Circle, Car, Plane, Train, Fish, Dog, Cat, Rabbit, Turtle, Panda, Squirrel, Star, Sparkles, Moon, 
  Gift, PartyPopper, Crown, Sword, Shield, Rainbow, ArrowLeft, 
  Watch, Lamp, Home, DoorOpen, AppWindow, Armchair, Bed, Toilet, 
  Monitor, Camera, Music, Heart, Smile, 
  Coffee, Pizza, Cake, Cookie, Popcorn, Beef, 
  Shirt, Glasses, Key, Umbrella, 
  Mountain, Waves, Leaf, Flame, Wind, 
  Zap, Snowflake, Ghost, Rocket, Bike, 
  Anchor, Bell, Bird, Bone, Bug, Sailboat, Ship, 
  Bus, Cherry, CloudRain, Compass, 
  Diamond, Hexagon, Dice5, Drum, Egg, 
  Eye, Feather, Footprints, Hammer, 
  Headphones, 
  Infinity, Laptop, Lightbulb, Flashlight, 
  Lock, Magnet, Mail, Map, MapPin, Luggage, 
  Mic, Microscope, Mouse, Palette, Paintbrush, 
  Paperclip, Pen, Phone, Piano, 
  Pill, Syringe, PlaneLanding, PlaneTakeoff, 
  Plug, Printer, Puzzle, Radio, 
  Recycle, Scissors, Search, 
  Shell, ShoppingCart, 
  Speaker, Sprout, 
  Stethoscope, Target, 
  Telescope, Tent, Thermometer, 
  Ticket, Trash2, Trophy, Medal, Truck, Tractor, 
  Tv, Wand2, Wine
} from 'lucide-react';
import { WordInfo } from './words';

export const GERMAN_WORD_LIST: WordInfo[] = [
  { word: 'SONNE', label: 'Sun', icon: Sun, imageUrl: 'https://loremflickr.com/200/200/sun,yellow/all' },
  { word: 'WOLKE', label: 'Cloud', icon: Cloud, imageUrl: 'https://loremflickr.com/200/200/cloud,sky/all' },
  { word: 'BLUME', label: 'Flower', icon: Flower, imageUrl: 'https://loremflickr.com/200/200/flower,garden/all' },
  { word: 'BAUM', label: 'Tree', icon: Trees, imageUrl: 'https://loremflickr.com/200/200/tree,green/all' },
  { word: 'BUCH', label: 'Book', icon: Book, imageUrl: 'https://loremflickr.com/200/200/book,library/all' },
  { word: 'WASSER', label: 'Water', icon: Droplet, imageUrl: 'https://loremflickr.com/200/200/water,splash/all' },
  { word: 'MILCH', label: 'Milk', icon: Milk, imageUrl: 'https://loremflickr.com/200/200/milk,glass/all' },
  { word: 'APFEL', label: 'Apple', icon: Apple, imageUrl: 'https://loremflickr.com/200/200/apple,fruit/all' },
  { word: 'BALL', label: 'Ball', icon: Circle, imageUrl: 'https://loremflickr.com/200/200/ball,soccer/all' },
  { word: 'AUTO', label: 'Car', icon: Car, imageUrl: 'https://loremflickr.com/200/200/car,auto/all' },
  { word: 'FLUGZEUG', label: 'Plane', icon: Plane, imageUrl: 'https://loremflickr.com/200/200/airplane,flight/all' },
  { word: 'ZUG', label: 'Train', icon: Train, imageUrl: 'https://loremflickr.com/200/200/train,rail/all' },
  { word: 'FISCH', label: 'Fish', icon: Fish, imageUrl: 'https://loremflickr.com/200/200/fish,ocean/all' },
  { word: 'HUND', label: 'Dog', icon: Dog, imageUrl: 'https://loremflickr.com/200/200/dog,puppy/all' },
  { word: 'KATZE', label: 'Cat', icon: Cat, imageUrl: 'https://loremflickr.com/200/200/cat,kitten/all' },
  { word: 'STERN', label: 'Star', icon: Star, imageUrl: 'https://loremflickr.com/200/200/star,night/all' },
  { word: 'MOND', label: 'Moon', icon: Moon, imageUrl: 'https://loremflickr.com/200/200/moon,night/all' },
  { word: 'GESCHENK', label: 'Gift', icon: Gift, imageUrl: 'https://loremflickr.com/200/200/gift,present/all' },
  { word: 'PARTY', label: 'Party', icon: PartyPopper, imageUrl: 'https://loremflickr.com/200/200/party,celebration/all' },
  { word: 'KRONE', label: 'Crown', icon: Crown, imageUrl: 'https://loremflickr.com/200/200/crown,gold/all' },
  { word: 'SCHWERT', label: 'Sword', icon: Sword, imageUrl: 'https://loremflickr.com/200/200/sword,knight/all' },
  { word: 'SCHILD', label: 'Shield', icon: Shield, imageUrl: 'https://loremflickr.com/200/200/shield,armor/all' },
  { word: 'REGENBOGEN', label: 'Rainbow', icon: Rainbow, imageUrl: 'https://loremflickr.com/200/200/rainbow,sky/all' },
  { word: 'PFEIL', label: 'Arrow', icon: ArrowLeft, imageUrl: 'https://loremflickr.com/200/200/arrow,sign/all' },
  { word: 'UHR', label: 'Clock', icon: Watch, imageUrl: 'https://loremflickr.com/200/200/clock,time/all' },
  { word: 'LAMPE', label: 'Lamp', icon: Lamp, imageUrl: 'https://loremflickr.com/200/200/lamp,light/all' },
  { word: 'HAUS', label: 'House', icon: Home, imageUrl: 'https://loremflickr.com/200/200/house,home/all' },
  { word: 'BILDSCHIRM', label: 'Monitor', icon: Monitor, imageUrl: 'https://loremflickr.com/200/200/computer,monitor/all' },
  { word: 'KAMERA', label: 'Camera', icon: Camera, imageUrl: 'https://loremflickr.com/200/200/camera,photo/all' },
  { word: 'MUSIK', label: 'Music', icon: Music, imageUrl: 'https://loremflickr.com/200/200/music,notes/all' },
  { word: 'HERZ', label: 'Heart', icon: Heart, imageUrl: 'https://loremflickr.com/200/200/heart,red/all' },
  { word: 'LÄCHELN', label: 'Smile', icon: Smile, imageUrl: 'https://loremflickr.com/200/200/smile,happy/all' },
  { word: 'KAFFEE', label: 'Coffee', icon: Coffee, imageUrl: 'https://loremflickr.com/200/200/coffee,cup/all' },
  { word: 'PIZZA', label: 'Pizza', icon: Pizza, imageUrl: 'https://loremflickr.com/200/200/pizza,food/all' },
  { word: 'KUCHEN', label: 'Cake', icon: Cake, imageUrl: 'https://loremflickr.com/200/200/cake,dessert/all' },
  { word: 'KEKS', label: 'Cookie', icon: Cookie, imageUrl: 'https://loremflickr.com/200/200/cookie,biscuit/all' },
  { word: 'HEMD', label: 'Shirt', icon: Shirt, imageUrl: 'https://loremflickr.com/200/200/shirt,clothing/all' },
  { word: 'BRILLE', label: 'Glasses', icon: Glasses, imageUrl: 'https://loremflickr.com/200/200/glasses,eyewear/all' },
  { word: 'SCHLÜSSEL', label: 'Key', icon: Key, imageUrl: 'https://loremflickr.com/200/200/key,metal/all' },
  { word: 'REGENSCHIRM', label: 'Umbrella', icon: Umbrella, imageUrl: 'https://loremflickr.com/200/200/umbrella,rain/all' },
  { word: 'BERG', label: 'Mountain', icon: Mountain, imageUrl: 'https://loremflickr.com/200/200/mountain,peak/all' },
  { word: 'WELLE', label: 'Sea', icon: Waves, imageUrl: 'https://loremflickr.com/200/200/sea,ocean/all' },
  { word: 'BLATT', label: 'Leaf', icon: Leaf, imageUrl: 'https://loremflickr.com/200/200/leaf,green/all' },
  { word: 'FEUER', label: 'Fire', icon: Flame, imageUrl: 'https://loremflickr.com/200/200/fire,flame/all' },
  { word: 'WIND', label: 'Wind', icon: Wind, imageUrl: 'https://loremflickr.com/200/200/wind,weather/all' },
  { word: 'BLITZ', label: 'Lightning', icon: Zap, imageUrl: 'https://loremflickr.com/200/200/lightning,storm/all' },
  { word: 'SCHNEE', label: 'Snow', icon: Snowflake, imageUrl: 'https://loremflickr.com/200/200/snow,winter/all' },
  { word: 'GEIST', label: 'Ghost', icon: Ghost, imageUrl: 'https://loremflickr.com/200/200/ghost,spooky/all' },
  { word: 'RAKETE', label: 'Rocket', icon: Rocket, imageUrl: 'https://loremflickr.com/200/200/rocket,space/all' },
  { word: 'FAHRRAD', label: 'Bike', icon: Bike, imageUrl: 'https://loremflickr.com/200/200/bicycle,bike/all' },
  { word: 'ANKER', label: 'Anchor', icon: Anchor, imageUrl: 'https://loremflickr.com/200/200/anchor,ship/all' },
  { word: 'GLOCKE', label: 'Bell', icon: Bell, imageUrl: 'https://loremflickr.com/200/200/bell,metal/all' },
  { word: 'VOGEL', label: 'Bird', icon: Bird, imageUrl: 'https://loremflickr.com/200/200/bird,animal/all' },
  { word: 'KNOCHEN', label: 'Bone', icon: Bone, imageUrl: 'https://loremflickr.com/200/200/bone,dog/all' },
  { word: 'KÄFER', label: 'Bug', icon: Bug, imageUrl: 'https://loremflickr.com/200/200/bug,insect/all' },
  { word: 'BUS', label: 'Bus', icon: Bus, imageUrl: 'https://loremflickr.com/200/200/bus,transport/all' },
  { word: 'KIRSCHE', label: 'Cherry', icon: Cherry, imageUrl: 'https://loremflickr.com/200/200/cherry,fruit/all' },
  { word: 'REGEN', label: 'Rain', icon: CloudRain, imageUrl: 'https://loremflickr.com/200/200/rain,weather/all' },
  { word: 'KOMPASS', label: 'Compass', icon: Compass, imageUrl: 'https://loremflickr.com/200/200/compass,direction/all' },
  { word: 'DIAMANT', label: 'Diamond', icon: Diamond, imageUrl: 'https://loremflickr.com/200/200/diamond,gem/all' },
  { word: 'WÜRFEL', label: 'Dice', icon: Dice5, imageUrl: 'https://loremflickr.com/200/200/dice,game/all' },
  { word: 'TROMMEL', label: 'Drum', icon: Drum, imageUrl: 'https://loremflickr.com/200/200/drum,music/all' },
  { word: 'EI', label: 'Egg', icon: Egg, imageUrl: 'https://loremflickr.com/200/200/egg,food/all' },
  { word: 'AUGE', label: 'Eye', icon: Eye, imageUrl: 'https://loremflickr.com/200/200/eye,vision/all' },
  { word: 'FEDER', label: 'Feather', icon: Feather, imageUrl: 'https://loremflickr.com/200/200/feather,bird/all' },
  { word: 'SPUREN', label: 'Footprints', icon: Footprints, imageUrl: 'https://loremflickr.com/200/200/footprints,sand/all' },
  { word: 'HAMMER', label: 'Hammer', icon: Hammer, imageUrl: 'https://loremflickr.com/200/200/hammer,tool/all' },
  { word: 'KOPFHÖRER', label: 'Headphones', icon: Headphones, imageUrl: 'https://loremflickr.com/200/200/headphones,music/all' },
  { word: 'UNENDLICH', label: 'Infinity', icon: Infinity, imageUrl: 'https://loremflickr.com/200/200/infinity,symbol/all' },
  { word: 'LAPTOP', label: 'Laptop', icon: Laptop, imageUrl: 'https://loremflickr.com/200/200/laptop,computer/all' },
  { word: 'BIRNE', label: 'Bulb', icon: Lightbulb, imageUrl: 'https://loremflickr.com/200/200/lightbulb,idea/all' },
  { word: 'SCHLOSS', label: 'Lock', icon: Lock, imageUrl: 'https://loremflickr.com/200/200/lock,secure/all' },
  { word: 'MAGNET', label: 'Magnet', icon: Magnet, imageUrl: 'https://loremflickr.com/200/200/magnet,metal/all' },
  { word: 'BRIEF', label: 'Mail', icon: Mail, imageUrl: 'https://loremflickr.com/200/200/letter,mail/all' },
  { word: 'KARTE', label: 'Map', icon: Map, imageUrl: 'https://loremflickr.com/200/200/map,world/all' },
  { word: 'NADEL', label: 'Pin', icon: MapPin, imageUrl: 'https://loremflickr.com/200/200/map,pin/all' },
  { word: 'MIKROFON', label: 'Mic', icon: Mic, imageUrl: 'https://loremflickr.com/200/200/microphone,voice/all' },
  { word: 'MIKROSKOP', label: 'Microscope', icon: Microscope, imageUrl: 'https://loremflickr.com/200/200/microscope,science/all' },
  { word: 'MAUS', label: 'Mouse', icon: Mouse, imageUrl: 'https://loremflickr.com/200/200/mouse,computer/all' },
  { word: 'PALETTE', label: 'Palette', icon: Palette, imageUrl: 'https://loremflickr.com/200/200/palette,color/all' },
  { word: 'BÜROKLAMMER', label: 'Paperclip', icon: Paperclip, imageUrl: 'https://loremflickr.com/200/200/paperclip,office/all' },
  { word: 'STIFT', label: 'Pen', icon: Pen, imageUrl: 'https://loremflickr.com/200/200/pen,writing/all' },
  { word: 'TELEFON', label: 'Phone', icon: Phone, imageUrl: 'https://loremflickr.com/200/200/phone,call/all' },
  { word: 'KLAVIER', label: 'Piano', icon: Piano, imageUrl: 'https://loremflickr.com/200/200/piano,music/all' },
  { word: 'PILLE', label: 'Pill', icon: Pill, imageUrl: 'https://loremflickr.com/200/200/pill,medicine/all' },
  { word: 'LANDUNG', label: 'Landing', icon: PlaneLanding, imageUrl: 'https://loremflickr.com/200/200/landing,plane/all' },
  { word: 'START', label: 'Takeoff', icon: PlaneTakeoff, imageUrl: 'https://loremflickr.com/200/200/takeoff,plane/all' },
  { word: 'STECKER', label: 'Plug', icon: Plug, imageUrl: 'https://loremflickr.com/200/200/plug,electric/all' },
  { word: 'DRUCKER', label: 'Printer', icon: Printer, imageUrl: 'https://loremflickr.com/200/200/printer,office/all' },
  { word: 'PUZZLE', label: 'Puzzle', icon: Puzzle, imageUrl: 'https://loremflickr.com/200/200/puzzle,piece/all' },
  { word: 'RADIO', label: 'Radio', icon: Radio, imageUrl: 'https://loremflickr.com/200/200/radio,music/all' },
  { word: 'RECYCLING', label: 'Recycle', icon: Recycle, imageUrl: 'https://loremflickr.com/200/200/recycle,symbol/all' },
  { word: 'SCHERE', label: 'Scissors', icon: Scissors, imageUrl: 'https://loremflickr.com/200/200/scissors,tool/all' },
  { word: 'SUCHE', label: 'Search', icon: Search, imageUrl: 'https://loremflickr.com/200/200/search,magnifier/all' },
  { word: 'MUSCHEL', label: 'Shell', icon: Shell, imageUrl: 'https://loremflickr.com/200/200/shell,beach/all' },
  { word: 'WAGEN', label: 'Cart', icon: ShoppingCart, imageUrl: 'https://loremflickr.com/200/200/shopping,cart/all' },
  { word: 'LAUTSPRECHER', label: 'Speaker', icon: Speaker, imageUrl: 'https://loremflickr.com/200/200/speaker,audio/all' },
  { word: 'SPROSS', label: 'Sprout', icon: Sprout, imageUrl: 'https://loremflickr.com/200/200/sprout,plant/all' },
  { word: 'STETHOSKOP', label: 'Stethoscope', icon: Stethoscope, imageUrl: 'https://loremflickr.com/200/200/stethoscope,medical/all' },
  { word: 'ZIEL', label: 'Target', icon: Target, imageUrl: 'https://loremflickr.com/200/200/target,aim/all' },
  { word: 'TELESKOP', label: 'Telescope', icon: Telescope, imageUrl: 'https://loremflickr.com/200/200/telescope,space/all' },
  { word: 'ZELT', label: 'Tent', icon: Tent, imageUrl: 'https://loremflickr.com/200/200/tent,camping/all' },
  { word: 'THERMOMETER', label: 'Thermometer', icon: Thermometer, imageUrl: 'https://loremflickr.com/200/200/thermometer,temp/all' },
  { word: 'TICKET', label: 'Ticket', icon: Ticket, imageUrl: 'https://loremflickr.com/200/200/ticket,entry/all' },
  { word: 'MÜLL', label: 'Trash', icon: Trash2, imageUrl: 'https://loremflickr.com/200/200/trash,bin/all' },
  { word: 'POKAL', label: 'Trophy', icon: Trophy, imageUrl: 'https://loremflickr.com/200/200/trophy,gold/all' },
  { word: 'LKW', label: 'Truck', icon: Truck, imageUrl: 'https://loremflickr.com/200/200/truck,transport/all' },
  { word: 'FERNSEHER', label: 'TV', icon: Tv, imageUrl: 'https://loremflickr.com/200/200/television,tv/all' },
  { word: 'ZAUBERSTAB', label: 'Wand', icon: Wand2, imageUrl: 'https://loremflickr.com/200/200/wand,magic/all' },
  { word: 'WEIN', label: 'Wine', icon: Wine, imageUrl: 'https://loremflickr.com/200/200/wine,glass/all' },
  { word: 'BANANE', label: 'Banana', icon: Banana, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'ZITRONE', label: 'Citrus', icon: Citrus, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'KAROTTE', label: 'Carrot', icon: Carrot, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'TRAUBE', label: 'Grape', icon: Grape, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'SUPPE', label: 'Soup', icon: Soup, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'EISCREME', label: 'IceCreamCone', icon: IceCreamCone, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'TÜR', label: 'Door', icon: DoorOpen, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'FENSTER', label: 'Window', icon: AppWindow, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'STUHL', label: 'Chair', icon: Armchair, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'BETT', label: 'Bed', icon: Bed, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'HASE', label: 'Rabbit', icon: Rabbit, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'SCHMETTERLING', label: 'Butterfly', icon: Sparkles, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'SCHILDKRÖTE', label: 'Turtle', icon: Turtle, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'HONIG', label: 'Honey', icon: Hexagon, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'BIBLIOTHEK', label: 'Library', icon: Library, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'PINSEL', label: 'Paintbrush', icon: Paintbrush, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'POPCORN', label: 'Popcorn', icon: Popcorn, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'STEAK', label: 'Steak', icon: Beef, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'TOILETTE', label: 'Toilet', icon: Toilet, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'SEGELBOOT', label: 'Sailboat', icon: Sailboat, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'SCHIFF', label: 'Ship', icon: Ship, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'TRAKTOR', label: 'Tractor', icon: Tractor, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'PANDA', label: 'Panda', icon: Panda, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'EICHHÖRNCHEN', label: 'Squirrel', icon: Squirrel, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'DELFIN', label: 'Dolphin', icon: Fish, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'OKTOPUS', label: 'Octopus', icon: Fish, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'HAI', label: 'Shark', icon: Fish, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'ROSE', label: 'Rose', icon: Rose, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'MEDAILLE', label: 'Medal', icon: Medal, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'RING', label: 'Ring', icon: Circle, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'GEPÄCK', label: 'Luggage', icon: Luggage, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'TASCHENLAMPE', label: 'Flashlight', icon: Flashlight, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'SPRITZE', label: 'Syringe', icon: Syringe, imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
];
