import { 
  Sun, Cloud, Flower, Rose, Trees, Book, Library, Droplet, Milk, Apple, 
  Banana, Citrus, Carrot, Grape, Soup, IceCreamCone,
  Circle, Car, Plane, Train, Fish, Dog, Cat, Rabbit, Turtle, Panda, Squirrel, Star, Sparkles, Moon, 
  Gift, PartyPopper, Crown, Sword, Shield, Rainbow, ArrowLeft, 
  Watch, Lamp, Home, DoorOpen, AppWindow, Armchair, Bed, Toilet, 
  Monitor, Camera, Music, Heart, Smile, 
  Coffee, Pizza, Cake, Cookie, Popcorn, Beef, 
  Shirt, Glasses, Key, Umbrella, 
  Mountain, Waves, Leaf, Flame, Wind, 
  Zap, Snowflake, Ghost, Rocket, Bike, 
  Anchor, Bell, Bird, Bone, Bug, Sailboat, Ship, 
  Bus, Cherry, CloudRain, Compass, 
  Diamond, Hexagon, Dice5, Drum, Egg, 
  Eye, Feather, Footprints, Hammer, 
  Headphones, 
  Infinity, Laptop, Lightbulb, Flashlight, 
  Lock, Magnet, Mail, Map, MapPin, Luggage, 
  Mic, Microscope, Mouse, Palette, Paintbrush, 
  Paperclip, Pen, Phone, Piano, 
  Pill, Syringe, PlaneLanding, PlaneTakeoff, 
  Plug, Printer, Puzzle, Radio, 
  Recycle, Scissors, Search, 
  Shell, ShoppingCart, 
  Speaker, Sprout, 
  Stethoscope, Target, 
  Telescope, Tent, Thermometer, 
  Ticket, Trash2, Trophy, Medal, Truck, Tractor, 
  Tv, Wand2, Wine
} from 'lucide-react';

export interface WordInfo {
  word: string;
  wordWithNiqqud?: string;
  icon: any;
  label: string;
  imageUrl: string;
}

export const WORD_LIST: WordInfo[] = [
  { word: 'שמש', wordWithNiqqud: 'שֶׁמֶשׁ', icon: Sun, label: 'Sun', imageUrl: 'https://loremflickr.com/200/200/sun,yellow/all' },
  { word: 'ענן', wordWithNiqqud: 'עָנָן', icon: Cloud, label: 'Cloud', imageUrl: 'https://loremflickr.com/200/200/cloud,sky/all' },
  { word: 'פרח', wordWithNiqqud: 'פֶּרַח', icon: Flower, label: 'Flower', imageUrl: 'https://loremflickr.com/200/200/flower,garden/all' },
  { word: 'עץ', wordWithNiqqud: 'עֵץ', icon: Trees, label: 'Tree', imageUrl: 'https://loremflickr.com/200/200/tree,green/all' },
  { word: 'ספר', wordWithNiqqud: 'סֵפֶר', icon: Book, label: 'Book', imageUrl: 'https://loremflickr.com/200/200/book,library/all' },
  { word: 'מים', wordWithNiqqud: 'מַיִם', icon: Droplet, label: 'Water', imageUrl: 'https://loremflickr.com/200/200/water,splash/all' },
  { word: 'חלב', wordWithNiqqud: 'חָלָב', icon: Milk, label: 'Milk', imageUrl: 'https://loremflickr.com/200/200/milk,glass/all' },
  { word: 'תפוח', wordWithNiqqud: 'תַּפּוּחַ', icon: Apple, label: 'Apple', imageUrl: 'https://loremflickr.com/200/200/apple,fruit/all' },
  { word: 'כדור', wordWithNiqqud: 'כַּדּוּר', icon: Circle, label: 'Ball', imageUrl: 'https://loremflickr.com/200/200/ball,soccer/all' },
  { word: 'אוטו', wordWithNiqqud: 'אוֹטוֹ', icon: Car, label: 'Car', imageUrl: 'https://loremflickr.com/200/200/car,auto/all' },
  { word: 'מטוס', wordWithNiqqud: 'מָטוֹס', icon: Plane, label: 'Plane', imageUrl: 'https://loremflickr.com/200/200/airplane,flight/all' },
  { word: 'רכבת', wordWithNiqqud: 'רַכֶּבֶת', icon: Train, label: 'Train', imageUrl: 'https://loremflickr.com/200/200/train,rail/all' },
  { word: 'דג', wordWithNiqqud: 'דָּג', icon: Fish, label: 'Fish', imageUrl: 'https://loremflickr.com/200/200/fish,ocean/all' },
  { word: 'כלב', wordWithNiqqud: 'כֶּלֶב', icon: Dog, label: 'Dog', imageUrl: 'https://loremflickr.com/200/200/dog,puppy/all' },
  { word: 'חתול', wordWithNiqqud: 'חָתוּל', icon: Cat, label: 'Cat', imageUrl: 'https://loremflickr.com/200/200/cat,kitten/all' },
  { word: 'כוכב', wordWithNiqqud: 'כּוֹכָב', icon: Star, label: 'Star', imageUrl: 'https://loremflickr.com/200/200/star,night/all' },
  { word: 'ירח', wordWithNiqqud: 'יָרֵחַ', icon: Moon, label: 'Moon', imageUrl: 'https://loremflickr.com/200/200/moon,night/all' },
  { word: 'מתנה', wordWithNiqqud: 'מַתָּנָה', icon: Gift, label: 'Gift', imageUrl: 'https://loremflickr.com/200/200/gift,present/all' },
  { word: 'מסיבה', wordWithNiqqud: 'מְסִבָּה', icon: PartyPopper, label: 'Party', imageUrl: 'https://loremflickr.com/200/200/party,celebration/all' },
  { word: 'כתר', wordWithNiqqud: 'כֶּתֶר', icon: Crown, label: 'Crown', imageUrl: 'https://loremflickr.com/200/200/crown,gold/all' },
  { word: 'חרב', wordWithNiqqud: 'חֶרֶב', icon: Sword, label: 'Sword', imageUrl: 'https://loremflickr.com/200/200/sword,knight/all' },
  { word: 'מגן', wordWithNiqqud: 'מָגֵן', icon: Shield, label: 'Shield', imageUrl: 'https://loremflickr.com/200/200/shield,armor/all' },
  { word: 'קשת', wordWithNiqqud: 'קֶשֶׁת', icon: Rainbow, label: 'Rainbow', imageUrl: 'https://loremflickr.com/200/200/rainbow,sky/all' },
  { word: 'חץ', wordWithNiqqud: 'חֵץ', icon: ArrowLeft, label: 'Arrow', imageUrl: 'https://loremflickr.com/200/200/arrow,sign/all' },
  { word: 'שעון', wordWithNiqqud: 'שָׁעוֹן', icon: Watch, label: 'Clock', imageUrl: 'https://loremflickr.com/200/200/clock,time/all' },
  { word: 'מנורה', wordWithNiqqud: 'מְנוֹרָה', icon: Lamp, label: 'Lamp', imageUrl: 'https://loremflickr.com/200/200/lamp,light/all' },
  { word: 'בית', wordWithNiqqud: 'בַּיִת', icon: Home, label: 'House', imageUrl: 'https://loremflickr.com/200/200/house,home/all' },
  { word: 'מסך', wordWithNiqqud: 'מָסָךְ', icon: Monitor, label: 'Monitor', imageUrl: 'https://loremflickr.com/200/200/computer,monitor/all' },
  { word: 'מצלמה', wordWithNiqqud: 'מַצְלֵמָה', icon: Camera, label: 'Camera', imageUrl: 'https://loremflickr.com/200/200/camera,photo/all' },
  { word: 'מוזיקה', wordWithNiqqud: 'מוּזִיקָה', icon: Music, label: 'Music', imageUrl: 'https://loremflickr.com/200/200/music,notes/all' },
  { word: 'לב', wordWithNiqqud: 'לֵב', icon: Heart, label: 'Heart', imageUrl: 'https://loremflickr.com/200/200/heart,red/all' },
  { word: 'חיוך', wordWithNiqqud: 'חִיּוּךְ', icon: Smile, label: 'Smile', imageUrl: 'https://loremflickr.com/200/200/smile,happy/all' },
  { word: 'קפה', wordWithNiqqud: 'קָפֶה', icon: Coffee, label: 'Coffee', imageUrl: 'https://loremflickr.com/200/200/coffee,cup/all' },
  { word: 'פיצה', wordWithNiqqud: 'פִּיצָה', icon: Pizza, label: 'Pizza', imageUrl: 'https://loremflickr.com/200/200/pizza,food/all' },
  { word: 'עוגה', wordWithNiqqud: 'עוּגָה', icon: Cake, label: 'Cake', imageUrl: 'https://loremflickr.com/200/200/cake,dessert/all' },
  { word: 'עוגיה', wordWithNiqqud: 'עוּגִיָּה', icon: Cookie, label: 'Cookie', imageUrl: 'https://loremflickr.com/200/200/cookie,biscuit/all' },
  { word: 'חולצה', wordWithNiqqud: 'חוּלְצָה', icon: Shirt, label: 'Shirt', imageUrl: 'https://loremflickr.com/200/200/shirt,clothing/all' },
  { word: 'משקפיים', wordWithNiqqud: 'מִשְׁקָפַיִם', icon: Glasses, label: 'Glasses', imageUrl: 'https://loremflickr.com/200/200/glasses,eyewear/all' },
  { word: 'מפתח', wordWithNiqqud: 'מַפְתֵּחַ', icon: Key, label: 'Key', imageUrl: 'https://loremflickr.com/200/200/key,metal/all' },
  { word: 'מטריה', wordWithNiqqud: 'מִטְרִיָּה', icon: Umbrella, label: 'Umbrella', imageUrl: 'https://loremflickr.com/200/200/umbrella,rain/all' },
  { word: 'הר', wordWithNiqqud: 'הַר', icon: Mountain, label: 'Mountain', imageUrl: 'https://loremflickr.com/200/200/mountain,peak/all' },
  { word: 'גל', wordWithNiqqud: 'גַּל', icon: Waves, label: 'Sea', imageUrl: 'https://loremflickr.com/200/200/sea,ocean/all' },
  { word: 'עלה', wordWithNiqqud: 'עָלֶה', icon: Leaf, label: 'Leaf', imageUrl: 'https://loremflickr.com/200/200/leaf,green/all' },
  { word: 'אש', wordWithNiqqud: 'אֵשׁ', icon: Flame, label: 'Fire', imageUrl: 'https://loremflickr.com/200/200/fire,flame/all' },
  { word: 'רוח', wordWithNiqqud: 'רוּחַ', icon: Wind, label: 'Wind', imageUrl: 'https://loremflickr.com/200/200/wind,weather/all' },
  { word: 'ברק', wordWithNiqqud: 'בָּרָק', icon: Zap, label: 'Lightning', imageUrl: 'https://loremflickr.com/200/200/lightning,storm/all' },
  { word: 'שלג', wordWithNiqqud: 'שֶׁלֶג', icon: Snowflake, label: 'Snow', imageUrl: 'https://loremflickr.com/200/200/snow,winter/all' },
  { word: 'שד', wordWithNiqqud: 'שֵׁד', icon: Ghost, label: 'Ghost', imageUrl: 'https://loremflickr.com/200/200/ghost,spooky/all' },
  { word: 'טיל', wordWithNiqqud: 'טִיל', icon: Rocket, label: 'Rocket', imageUrl: 'https://loremflickr.com/200/200/rocket,space/all' },
  { word: 'אופניים', wordWithNiqqud: 'אוֹפַנַּיִם', icon: Bike, label: 'Bike', imageUrl: 'https://loremflickr.com/200/200/bicycle,bike/all' },
  { word: 'עוגן', wordWithNiqqud: 'עוֹגֶן', icon: Anchor, label: 'Anchor', imageUrl: 'https://loremflickr.com/200/200/anchor,ship/all' },
  { word: 'פעמון', wordWithNiqqud: 'פַּעֲמוֹן', icon: Bell, label: 'Bell', imageUrl: 'https://loremflickr.com/200/200/bell,metal/all' },
  { word: 'ציפור', wordWithNiqqud: 'צִיפּוֹר', icon: Bird, label: 'Bird', imageUrl: 'https://loremflickr.com/200/200/bird,animal/all' },
  { word: 'עצם', wordWithNiqqud: 'עֶצֶם', icon: Bone, label: 'Bone', imageUrl: 'https://loremflickr.com/200/200/bone,dog/all' },
  { word: 'חיפושית', wordWithNiqqud: 'חִיפּוּשִׁית', icon: Bug, label: 'Bug', imageUrl: 'https://loremflickr.com/200/200/bug,insect/all' },
  { word: 'אוטובוס', wordWithNiqqud: 'אוֹטוֹבּוּס', icon: Bus, label: 'Bus', imageUrl: 'https://loremflickr.com/200/200/bus,transport/all' },
  { word: 'דובדבן', wordWithNiqqud: 'דּוּבְדְּבָן', icon: Cherry, label: 'Cherry', imageUrl: 'https://loremflickr.com/200/200/cherry,fruit/all' },
  { word: 'גשם', wordWithNiqqud: 'גֶּשֶׁם', icon: CloudRain, label: 'Rain', imageUrl: 'https://loremflickr.com/200/200/rain,weather/all' },
  { word: 'מצפן', wordWithNiqqud: 'מַצְפֵּן', icon: Compass, label: 'Compass', imageUrl: 'https://loremflickr.com/200/200/compass,direction/all' },
  { word: 'יהלום', wordWithNiqqud: 'יַהֲלוֹם', icon: Diamond, label: 'Diamond', imageUrl: 'https://loremflickr.com/200/200/diamond,gem/all' },
  { word: 'קוביה', wordWithNiqqud: 'קוּבִּיָּה', icon: Dice5, label: 'Dice', imageUrl: 'https://loremflickr.com/200/200/dice,game/all' },
  { word: 'תוף', wordWithNiqqud: 'תּוֹף', icon: Drum, label: 'Drum', imageUrl: 'https://loremflickr.com/200/200/drum,music/all' },
  { word: 'ביצה', wordWithNiqqud: 'בֵּיצָה', icon: Egg, label: 'Egg', imageUrl: 'https://loremflickr.com/200/200/egg,food/all' },
  { word: 'עין', wordWithNiqqud: 'עַיִן', icon: Eye, label: 'Eye', imageUrl: 'https://loremflickr.com/200/200/eye,vision/all' },
  { word: 'נוצה', wordWithNiqqud: 'נוֹצָה', icon: Feather, label: 'Feather', imageUrl: 'https://loremflickr.com/200/200/feather,bird/all' },
  { word: 'עקבות', wordWithNiqqud: 'עֲקֵבוֹת', icon: Footprints, label: 'Footprints', imageUrl: 'https://loremflickr.com/200/200/footprints,sand/all' },
  { word: 'פטיש', wordWithNiqqud: 'פַּטִּישׁ', icon: Hammer, label: 'Hammer', imageUrl: 'https://loremflickr.com/200/200/hammer,tool/all' },
  { word: 'אוזניות', wordWithNiqqud: 'אוֹזְנִיּוֹת', icon: Headphones, label: 'Headphones', imageUrl: 'https://loremflickr.com/200/200/headphones,music/all' },
  { word: 'אינסוף', wordWithNiqqud: 'אֵינְסוֹף', icon: Infinity, label: 'Infinity', imageUrl: 'https://loremflickr.com/200/200/infinity,symbol/all' },
  { word: 'לפטופ', wordWithNiqqud: 'לַפְּטוֹפּ', icon: Laptop, label: 'Laptop', imageUrl: 'https://loremflickr.com/200/200/laptop,computer/all' },
  { word: 'נורה', wordWithNiqqud: 'נוּרָה', icon: Lightbulb, label: 'Bulb', imageUrl: 'https://loremflickr.com/200/200/lightbulb,idea/all' },
  { word: 'מנעול', wordWithNiqqud: 'מַנְעוּל', icon: Lock, label: 'Lock', imageUrl: 'https://loremflickr.com/200/200/lock,secure/all' },
  { word: 'מגנט', wordWithNiqqud: 'מַגְנֵט', icon: Magnet, label: 'Magnet', imageUrl: 'https://loremflickr.com/200/200/magnet,metal/all' },
  { word: 'מכתב', wordWithNiqqud: 'מִכְתָּב', icon: Mail, label: 'Mail', imageUrl: 'https://loremflickr.com/200/200/letter,mail/all' },
  { word: 'מפה', wordWithNiqqud: 'מַפָּה', icon: Map, label: 'Map', imageUrl: 'https://loremflickr.com/200/200/map,world/all' },
  { word: 'סיכה', wordWithNiqqud: 'סִיכָּה', icon: MapPin, label: 'Pin', imageUrl: 'https://loremflickr.com/200/200/map,pin/all' },
  { word: 'מיקרופון', wordWithNiqqud: 'מִיקְרוֹפוֹן', icon: Mic, label: 'Mic', imageUrl: 'https://loremflickr.com/200/200/microphone,voice/all' },
  { word: 'מיקרוסקופ', wordWithNiqqud: 'מִיקְרוֹסְקוֹפּ', icon: Microscope, label: 'Microscope', imageUrl: 'https://loremflickr.com/200/200/microscope,science/all' },
  { word: 'עכבר', wordWithNiqqud: 'עַכְבָּר', icon: Mouse, label: 'Mouse', imageUrl: 'https://loremflickr.com/200/200/mouse,computer/all' },
  { word: 'פלטה', wordWithNiqqud: 'פָּלֵטָה', icon: Palette, label: 'Palette', imageUrl: 'https://loremflickr.com/200/200/palette,color/all' },
  { word: 'אטב', wordWithNiqqud: 'אֶטָב', icon: Paperclip, label: 'Paperclip', imageUrl: 'https://loremflickr.com/200/200/paperclip,office/all' },
  { word: 'עט', wordWithNiqqud: 'עֵט', icon: Pen, label: 'Pen', imageUrl: 'https://loremflickr.com/200/200/pen,writing/all' },
  { word: 'טלפון', wordWithNiqqud: 'טֶלֶפוֹן', icon: Phone, label: 'Phone', imageUrl: 'https://loremflickr.com/200/200/phone,call/all' },
  { word: 'פסנתר', wordWithNiqqud: 'פְּסַנְתֵּר', icon: Piano, label: 'Piano', imageUrl: 'https://loremflickr.com/200/200/piano,music/all' },
  { word: 'תרופה', wordWithNiqqud: 'תְּרוּפָה', icon: Pill, label: 'Pill', imageUrl: 'https://loremflickr.com/200/200/pill,medicine/all' },
  { word: 'נחיתה', wordWithNiqqud: 'נְחִיתָה', icon: PlaneLanding, label: 'Landing', imageUrl: 'https://loremflickr.com/200/200/landing,plane/all' },
  { word: 'המראה', wordWithNiqqud: 'הַמְרָאָה', icon: PlaneTakeoff, label: 'Takeoff', imageUrl: 'https://loremflickr.com/200/200/takeoff,plane/all' },
  { word: 'תקע', wordWithNiqqud: 'תֶּקַע', icon: Plug, label: 'Plug', imageUrl: 'https://loremflickr.com/200/200/plug,electric/all' },
  { word: 'מדפסת', wordWithNiqqud: 'מַדְפֶּסֶת', icon: Printer, label: 'Printer', imageUrl: 'https://loremflickr.com/200/200/printer,office/all' },
  { word: 'פאזל', wordWithNiqqud: 'פָּאזֶל', icon: Puzzle, label: 'Puzzle', imageUrl: 'https://loremflickr.com/200/200/puzzle,piece/all' },
  { word: 'רדיו', wordWithNiqqud: 'רַדְיוֹ', icon: Radio, label: 'Radio', imageUrl: 'https://loremflickr.com/200/200/radio,music/all' },
  { word: 'מיחזור', wordWithNiqqud: 'מִיחְזוּר', icon: Recycle, label: 'Recycle', imageUrl: 'https://loremflickr.com/200/200/recycle,symbol/all' },
  { word: 'מספריים', wordWithNiqqud: 'מִסְפָּרַיִם', icon: Scissors, label: 'Scissors', imageUrl: 'https://loremflickr.com/200/200/scissors,tool/all' },
  { word: 'זכוכית מגדלת', wordWithNiqqud: 'זְכוּכִית מַגְדֶּלֶת', icon: Search, label: 'Search', imageUrl: 'https://loremflickr.com/200/200/search,magnifier/all' },
  { word: 'צדף', wordWithNiqqud: 'צֶדֶף', icon: Shell, label: 'Shell', imageUrl: 'https://loremflickr.com/200/200/shell,beach/all' },
  { word: 'עגלה', wordWithNiqqud: 'עֲגָלָה', icon: ShoppingCart, label: 'Cart', imageUrl: 'https://loremflickr.com/200/200/shopping,cart/all' },
  { word: 'רמקול', wordWithNiqqud: 'רַמְקוֹל', icon: Speaker, label: 'Speaker', imageUrl: 'https://loremflickr.com/200/200/speaker,audio/all' },
  { word: 'נבט', wordWithNiqqud: 'נֶבֶט', icon: Sprout, label: 'Sprout', imageUrl: 'https://loremflickr.com/200/200/sprout,plant/all' },
  { word: 'סטטוסקופ', wordWithNiqqud: 'סְטֶטוֹסְקוֹפּ', icon: Stethoscope, label: 'Stethoscope', imageUrl: 'https://loremflickr.com/200/200/stethoscope,medical/all' },
  { word: 'מטרה', wordWithNiqqud: 'מַטָּרָה', icon: Target, label: 'Target', imageUrl: 'https://loremflickr.com/200/200/target,aim/all' },
  { word: 'טלסקופ', wordWithNiqqud: 'טֶלֶסְקוֹפּ', icon: Telescope, label: 'Telescope', imageUrl: 'https://loremflickr.com/200/200/telescope,space/all' },
  { word: 'אוהל', wordWithNiqqud: 'אוֹהֶל', icon: Tent, label: 'Tent', imageUrl: 'https://loremflickr.com/200/200/tent,camping/all' },
  { word: 'מדחום', wordWithNiqqud: 'מַדְחוֹם', icon: Thermometer, label: 'Thermometer', imageUrl: 'https://loremflickr.com/200/200/thermometer,temp/all' },
  { word: 'כרטיס', wordWithNiqqud: 'כַּרְטִיס', icon: Ticket, label: 'Ticket', imageUrl: 'https://loremflickr.com/200/200/ticket,entry/all' },
  { word: 'פח', wordWithNiqqud: 'פַּח', icon: Trash2, label: 'Trash', imageUrl: 'https://loremflickr.com/200/200/trash,bin/all' },
  { word: 'גביע', wordWithNiqqud: 'גָּבִיעַ', icon: Trophy, label: 'Trophy', imageUrl: 'https://loremflickr.com/200/200/trophy,gold/all' },
  { word: 'משאית', wordWithNiqqud: 'מַשָּׂאִית', icon: Truck, label: 'Truck', imageUrl: 'https://loremflickr.com/200/200/truck,transport/all' },
  { word: 'טלוויזיה', wordWithNiqqud: 'טֶלֶוִויזְיָה', icon: Tv, label: 'TV', imageUrl: 'https://loremflickr.com/200/200/television,tv/all' },
  { word: 'שרביט', wordWithNiqqud: 'שַׁרְבִיט', icon: Wand2, label: 'Wand', imageUrl: 'https://loremflickr.com/200/200/wand,magic/all' },
  { word: 'יין', wordWithNiqqud: 'יַיִן', icon: Wine, label: 'Wine', imageUrl: 'https://loremflickr.com/200/200/wine,glass/all' },
  { word: 'בננה', wordWithNiqqud: 'בָּנָנָה', icon: Banana, label: 'Banana', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'תפוז', wordWithNiqqud: 'תַּפּוּז', icon: Citrus, label: 'Citrus', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'גזר', wordWithNiqqud: 'גֶּזֶר', icon: Carrot, label: 'Carrot', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'ענבים', wordWithNiqqud: 'עֲנָבִים', icon: Grape, label: 'Grape', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'מרק', wordWithNiqqud: 'מָרָק', icon: Soup, label: 'Soup', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'גלידה', wordWithNiqqud: 'גְּלִידָה', icon: IceCreamCone, label: 'IceCreamCone', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'דלת', wordWithNiqqud: 'דֶּלֶת', icon: DoorOpen, label: 'Door', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'חלון', wordWithNiqqud: 'חַלּוֹן', icon: AppWindow, label: 'Window', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'כיסא', wordWithNiqqud: 'כִּיסֵּא', icon: Armchair, label: 'Chair', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'מיטה', wordWithNiqqud: 'מִיטָּה', icon: Bed, label: 'Bed', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'ארנב', wordWithNiqqud: 'אַרְנָב', icon: Rabbit, label: 'Rabbit', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'פרפר', wordWithNiqqud: 'פַּרְפַּר', icon: Sparkles, label: 'Butterfly', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'צב', wordWithNiqqud: 'צָב', icon: Turtle, label: 'Turtle', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'דבש', wordWithNiqqud: 'דְּבַשׁ', icon: Hexagon, label: 'Honey', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'ספרים', wordWithNiqqud: 'סְפָרִים', icon: Library, label: 'Library', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'מברשת', wordWithNiqqud: 'מִבְרֶשֶׁת', icon: Paintbrush, label: 'Paintbrush', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'פופקורן', wordWithNiqqud: 'פּוֹפְקוֹרְן', icon: Popcorn, label: 'Popcorn', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'סטייק', wordWithNiqqud: 'סְטֵייק', icon: Beef, label: 'Steak', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'אסלה', wordWithNiqqud: 'אַסְלָה', icon: Toilet, label: 'Toilet', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'סירה', wordWithNiqqud: 'סִירָה', icon: Sailboat, label: 'Sailboat', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'אוניה', wordWithNiqqud: 'אוֹנִיָּה', icon: Ship, label: 'Ship', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'טרקטור', wordWithNiqqud: 'טְרַקְטוֹר', icon: Tractor, label: 'Tractor', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'פנדה', wordWithNiqqud: 'פַּנְדָּה', icon: Panda, label: 'Panda', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'סנאי', wordWithNiqqud: 'סְנָאִי', icon: Squirrel, label: 'Squirrel', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'דולפין', wordWithNiqqud: 'דּוֹלְפִין', icon: Fish, label: 'Dolphin', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'תמנון', wordWithNiqqud: 'תְּמָנוּן', icon: Fish, label: 'Octopus', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'כריש', wordWithNiqqud: 'כָּרִישׁ', icon: Fish, label: 'Shark', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'ורד', wordWithNiqqud: 'וֶרֶד', icon: Rose, label: 'Rose', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'מדליה', wordWithNiqqud: 'מֵדַלְיָה', icon: Medal, label: 'Medal', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'טבעת', wordWithNiqqud: 'טַבַּעַת', icon: Circle, label: 'Ring', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'מזוודה', wordWithNiqqud: 'מִזְוָודָה', icon: Luggage, label: 'Luggage', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'פנס', wordWithNiqqud: 'פָּנָס', icon: Flashlight, label: 'Flashlight', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
  { word: 'מזרק', wordWithNiqqud: 'מַזְרֵק', icon: Syringe, label: 'Syringe', imageUrl: 'https://loremflickr.com/200/200/placeholder/all' },
];
