import { 
  Sun, Cloud, Flower, Trees, Book, Droplet, Milk, Apple, 
  Circle, Car, Plane, Train, Fish, Dog, Cat, Star, Moon, 
  Gift, PartyPopper, Crown, Sword, Shield, Rainbow, ArrowLeft, 
  Watch, Lamp, Home, 
  Monitor, Camera, Music, Heart, Smile, 
  Coffee, Pizza, Cake, Cookie, 
  Shirt, Glasses, Key, Umbrella, 
  Mountain, Waves, Leaf, Flame, Wind, 
  Zap, Snowflake, Ghost, Rocket, Bike, 
  Anchor, Bell, Bird, Bone, Bug, 
  Bus, Cherry, CloudRain, Compass, 
  Diamond, Dice5, Drum, Egg, 
  Eye, Feather, Footprints, Hammer, 
  Headphones, 
  Infinity, Laptop, Lightbulb, 
  Lock, Magnet, Mail, Map, MapPin, 
  Mic, Microscope, Mouse, Palette, 
  Paperclip, Pen, Phone, Piano, 
  Pill, PlaneLanding, PlaneTakeoff, 
  Plug, Printer, Puzzle, Radio, 
  Recycle, Scissors, Search, 
  Shell, ShoppingCart, 
  Speaker, Sprout, 
  Stethoscope, Target, 
  Telescope, Tent, Thermometer, 
  Ticket, Trash2, Trophy, Truck, 
  Tv, Wand2, Wine
} from 'lucide-react';

export interface WordInfo {
  word: string;
  icon: any;
  label: string;
  imageUrl: string;
}

export const WORD_LIST: WordInfo[] = [
  { word: 'שמש', icon: Sun, label: 'Sun', imageUrl: 'https://loremflickr.com/200/200/sun,yellow/all' },
  { word: 'ענן', icon: Cloud, label: 'Cloud', imageUrl: 'https://loremflickr.com/200/200/cloud,sky/all' },
  { word: 'פרח', icon: Flower, label: 'Flower', imageUrl: 'https://loremflickr.com/200/200/flower,garden/all' },
  { word: 'עץ', icon: Trees, label: 'Tree', imageUrl: 'https://loremflickr.com/200/200/tree,green/all' },
  { word: 'ספר', icon: Book, label: 'Book', imageUrl: 'https://loremflickr.com/200/200/book,library/all' },
  { word: 'מים', icon: Droplet, label: 'Water', imageUrl: 'https://loremflickr.com/200/200/water,splash/all' },
  { word: 'חלב', icon: Milk, label: 'Milk', imageUrl: 'https://loremflickr.com/200/200/milk,glass/all' },
  { word: 'תפוח', icon: Apple, label: 'Apple', imageUrl: 'https://loremflickr.com/200/200/apple,fruit/all' },
  { word: 'כדור', icon: Circle, label: 'Ball', imageUrl: 'https://loremflickr.com/200/200/ball,soccer/all' },
  { word: 'אוטו', icon: Car, label: 'Car', imageUrl: 'https://loremflickr.com/200/200/car,auto/all' },
  { word: 'מטוס', icon: Plane, label: 'Plane', imageUrl: 'https://loremflickr.com/200/200/airplane,flight/all' },
  { word: 'רכבת', icon: Train, label: 'Train', imageUrl: 'https://loremflickr.com/200/200/train,rail/all' },
  { word: 'דג', icon: Fish, label: 'Fish', imageUrl: 'https://loremflickr.com/200/200/fish,ocean/all' },
  { word: 'כלב', icon: Dog, label: 'Dog', imageUrl: 'https://loremflickr.com/200/200/dog,puppy/all' },
  { word: 'חתול', icon: Cat, label: 'Cat', imageUrl: 'https://loremflickr.com/200/200/cat,kitten/all' },
  { word: 'כוכב', icon: Star, label: 'Star', imageUrl: 'https://loremflickr.com/200/200/star,night/all' },
  { word: 'ירח', icon: Moon, label: 'Moon', imageUrl: 'https://loremflickr.com/200/200/moon,night/all' },
  { word: 'מתנה', icon: Gift, label: 'Gift', imageUrl: 'https://loremflickr.com/200/200/gift,present/all' },
  { word: 'מסיבה', icon: PartyPopper, label: 'Party', imageUrl: 'https://loremflickr.com/200/200/party,celebration/all' },
  { word: 'כתר', icon: Crown, label: 'Crown', imageUrl: 'https://loremflickr.com/200/200/crown,gold/all' },
  { word: 'חרב', icon: Sword, label: 'Sword', imageUrl: 'https://loremflickr.com/200/200/sword,knight/all' },
  { word: 'מגן', icon: Shield, label: 'Shield', imageUrl: 'https://loremflickr.com/200/200/shield,armor/all' },
  { word: 'קשת', icon: Rainbow, label: 'Rainbow', imageUrl: 'https://loremflickr.com/200/200/rainbow,sky/all' },
  { word: 'חץ', icon: ArrowLeft, label: 'Arrow', imageUrl: 'https://loremflickr.com/200/200/arrow,sign/all' },
  { word: 'שעון', icon: Watch, label: 'Clock', imageUrl: 'https://loremflickr.com/200/200/clock,time/all' },
  { word: 'מנורה', icon: Lamp, label: 'Lamp', imageUrl: 'https://loremflickr.com/200/200/lamp,light/all' },
  { word: 'בית', icon: Home, label: 'House', imageUrl: 'https://loremflickr.com/200/200/house,home/all' },
  { word: 'מסך', icon: Monitor, label: 'Monitor', imageUrl: 'https://loremflickr.com/200/200/computer,monitor/all' },
  { word: 'מצלמה', icon: Camera, label: 'Camera', imageUrl: 'https://loremflickr.com/200/200/camera,photo/all' },
  { word: 'מוזיקה', icon: Music, label: 'Music', imageUrl: 'https://loremflickr.com/200/200/music,notes/all' },
  { word: 'לב', icon: Heart, label: 'Heart', imageUrl: 'https://loremflickr.com/200/200/heart,red/all' },
  { word: 'חיוך', icon: Smile, label: 'Smile', imageUrl: 'https://loremflickr.com/200/200/smile,happy/all' },
  { word: 'קפה', icon: Coffee, label: 'Coffee', imageUrl: 'https://loremflickr.com/200/200/coffee,cup/all' },
  { word: 'פיצה', icon: Pizza, label: 'Pizza', imageUrl: 'https://loremflickr.com/200/200/pizza,food/all' },
  { word: 'עוגה', icon: Cake, label: 'Cake', imageUrl: 'https://loremflickr.com/200/200/cake,dessert/all' },
  { word: 'עוגיה', icon: Cookie, label: 'Cookie', imageUrl: 'https://loremflickr.com/200/200/cookie,biscuit/all' },
  { word: 'חולצה', icon: Shirt, label: 'Shirt', imageUrl: 'https://loremflickr.com/200/200/shirt,clothing/all' },
  { word: 'משקפיים', icon: Glasses, label: 'Glasses', imageUrl: 'https://loremflickr.com/200/200/glasses,eyewear/all' },
  { word: 'מפתח', icon: Key, label: 'Key', imageUrl: 'https://loremflickr.com/200/200/key,metal/all' },
  { word: 'מטריה', icon: Umbrella, label: 'Umbrella', imageUrl: 'https://loremflickr.com/200/200/umbrella,rain/all' },
  { word: 'הר', icon: Mountain, label: 'Mountain', imageUrl: 'https://loremflickr.com/200/200/mountain,peak/all' },
  { word: 'ים', icon: Waves, label: 'Sea', imageUrl: 'https://loremflickr.com/200/200/sea,ocean/all' },
  { word: 'עלה', icon: Leaf, label: 'Leaf', imageUrl: 'https://loremflickr.com/200/200/leaf,green/all' },
  { word: 'אש', icon: Flame, label: 'Fire', imageUrl: 'https://loremflickr.com/200/200/fire,flame/all' },
  { word: 'רוח', icon: Wind, label: 'Wind', imageUrl: 'https://loremflickr.com/200/200/wind,weather/all' },
  { word: 'ברק', icon: Zap, label: 'Lightning', imageUrl: 'https://loremflickr.com/200/200/lightning,storm/all' },
  { word: 'שלג', icon: Snowflake, label: 'Snow', imageUrl: 'https://loremflickr.com/200/200/snow,winter/all' },
  { word: 'שד', icon: Ghost, label: 'Ghost', imageUrl: 'https://loremflickr.com/200/200/ghost,spooky/all' },
  { word: 'טיל', icon: Rocket, label: 'Rocket', imageUrl: 'https://loremflickr.com/200/200/rocket,space/all' },
  { word: 'אופניים', icon: Bike, label: 'Bike', imageUrl: 'https://loremflickr.com/200/200/bicycle,bike/all' },
  { word: 'עוגן', icon: Anchor, label: 'Anchor', imageUrl: 'https://loremflickr.com/200/200/anchor,ship/all' },
  { word: 'פעמון', icon: Bell, label: 'Bell', imageUrl: 'https://loremflickr.com/200/200/bell,metal/all' },
  { word: 'ציפור', icon: Bird, label: 'Bird', imageUrl: 'https://loremflickr.com/200/200/bird,animal/all' },
  { word: 'עצם', icon: Bone, label: 'Bone', imageUrl: 'https://loremflickr.com/200/200/bone,dog/all' },
  { word: 'חיפושית', icon: Bug, label: 'Bug', imageUrl: 'https://loremflickr.com/200/200/bug,insect/all' },
  { word: 'אוטובוס', icon: Bus, label: 'Bus', imageUrl: 'https://loremflickr.com/200/200/bus,transport/all' },
  { word: 'דובדבן', icon: Cherry, label: 'Cherry', imageUrl: 'https://loremflickr.com/200/200/cherry,fruit/all' },
  { word: 'גשם', icon: CloudRain, label: 'Rain', imageUrl: 'https://loremflickr.com/200/200/rain,weather/all' },
  { word: 'מצפן', icon: Compass, label: 'Compass', imageUrl: 'https://loremflickr.com/200/200/compass,direction/all' },
  { word: 'יהלום', icon: Diamond, label: 'Diamond', imageUrl: 'https://loremflickr.com/200/200/diamond,gem/all' },
  { word: 'קוביה', icon: Dice5, label: 'Dice', imageUrl: 'https://loremflickr.com/200/200/dice,game/all' },
  { word: 'תוף', icon: Drum, label: 'Drum', imageUrl: 'https://loremflickr.com/200/200/drum,music/all' },
  { word: 'ביצה', icon: Egg, label: 'Egg', imageUrl: 'https://loremflickr.com/200/200/egg,food/all' },
  { word: 'עין', icon: Eye, label: 'Eye', imageUrl: 'https://loremflickr.com/200/200/eye,vision/all' },
  { word: 'נוצה', icon: Feather, label: 'Feather', imageUrl: 'https://loremflickr.com/200/200/feather,bird/all' },
  { word: 'עקבות', icon: Footprints, label: 'Footprints', imageUrl: 'https://loremflickr.com/200/200/footprints,sand/all' },
  { word: 'פטיש', icon: Hammer, label: 'Hammer', imageUrl: 'https://loremflickr.com/200/200/hammer,tool/all' },
  { word: 'אוזניות', icon: Headphones, label: 'Headphones', imageUrl: 'https://loremflickr.com/200/200/headphones,music/all' },
  { word: 'אינסוף', icon: Infinity, label: 'Infinity', imageUrl: 'https://loremflickr.com/200/200/infinity,symbol/all' },
  { word: 'לפטופ', icon: Laptop, label: 'Laptop', imageUrl: 'https://loremflickr.com/200/200/laptop,computer/all' },
  { word: 'נורה', icon: Lightbulb, label: 'Bulb', imageUrl: 'https://loremflickr.com/200/200/lightbulb,idea/all' },
  { word: 'מנעול', icon: Lock, label: 'Lock', imageUrl: 'https://loremflickr.com/200/200/lock,secure/all' },
  { word: 'מגנט', icon: Magnet, label: 'Magnet', imageUrl: 'https://loremflickr.com/200/200/magnet,metal/all' },
  { word: 'מכתב', icon: Mail, label: 'Mail', imageUrl: 'https://loremflickr.com/200/200/letter,mail/all' },
  { word: 'מפה', icon: Map, label: 'Map', imageUrl: 'https://loremflickr.com/200/200/map,world/all' },
  { word: 'סיכה', icon: MapPin, label: 'Pin', imageUrl: 'https://loremflickr.com/200/200/map,pin/all' },
  { word: 'מיקרופון', icon: Mic, label: 'Mic', imageUrl: 'https://loremflickr.com/200/200/microphone,voice/all' },
  { word: 'מיקרוסקופ', icon: Microscope, label: 'Microscope', imageUrl: 'https://loremflickr.com/200/200/microscope,science/all' },
  { word: 'עכבר', icon: Mouse, label: 'Mouse', imageUrl: 'https://loremflickr.com/200/200/mouse,computer/all' },
  { word: 'פלטה', icon: Palette, label: 'Palette', imageUrl: 'https://loremflickr.com/200/200/palette,color/all' },
  { word: 'אטב', icon: Paperclip, label: 'Paperclip', imageUrl: 'https://loremflickr.com/200/200/paperclip,office/all' },
  { word: 'עט', icon: Pen, label: 'Pen', imageUrl: 'https://loremflickr.com/200/200/pen,writing/all' },
  { word: 'טלפון', icon: Phone, label: 'Phone', imageUrl: 'https://loremflickr.com/200/200/phone,call/all' },
  { word: 'פסנתר', icon: Piano, label: 'Piano', imageUrl: 'https://loremflickr.com/200/200/piano,music/all' },
  { word: 'תרופה', icon: Pill, label: 'Pill', imageUrl: 'https://loremflickr.com/200/200/pill,medicine/all' },
  { word: 'נחיתה', icon: PlaneLanding, label: 'Landing', imageUrl: 'https://loremflickr.com/200/200/landing,plane/all' },
  { word: 'המראה', icon: PlaneTakeoff, label: 'Takeoff', imageUrl: 'https://loremflickr.com/200/200/takeoff,plane/all' },
  { word: 'תקע', icon: Plug, label: 'Plug', imageUrl: 'https://loremflickr.com/200/200/plug,electric/all' },
  { word: 'מדפסת', icon: Printer, label: 'Printer', imageUrl: 'https://loremflickr.com/200/200/printer,office/all' },
  { word: 'פאזל', icon: Puzzle, label: 'Puzzle', imageUrl: 'https://loremflickr.com/200/200/puzzle,piece/all' },
  { word: 'רדיו', icon: Radio, label: 'Radio', imageUrl: 'https://loremflickr.com/200/200/radio,music/all' },
  { word: 'מיחזור', icon: Recycle, label: 'Recycle', imageUrl: 'https://loremflickr.com/200/200/recycle,symbol/all' },
  { word: 'מספריים', icon: Scissors, label: 'Scissors', imageUrl: 'https://loremflickr.com/200/200/scissors,tool/all' },
  { word: 'זכוכית מגדלת', icon: Search, label: 'Search', imageUrl: 'https://loremflickr.com/200/200/search,magnifier/all' },
  { word: 'צדף', icon: Shell, label: 'Shell', imageUrl: 'https://loremflickr.com/200/200/shell,beach/all' },
  { word: 'עגלה', icon: ShoppingCart, label: 'Cart', imageUrl: 'https://loremflickr.com/200/200/shopping,cart/all' },
  { word: 'רמקול', icon: Speaker, label: 'Speaker', imageUrl: 'https://loremflickr.com/200/200/speaker,audio/all' },
  { word: 'נבט', icon: Sprout, label: 'Sprout', imageUrl: 'https://loremflickr.com/200/200/sprout,plant/all' },
  { word: 'סטטוסקופ', icon: Stethoscope, label: 'Stethoscope', imageUrl: 'https://loremflickr.com/200/200/stethoscope,medical/all' },
  { word: 'מטרה', icon: Target, label: 'Target', imageUrl: 'https://loremflickr.com/200/200/target,aim/all' },
  { word: 'טלסקופ', icon: Telescope, label: 'Telescope', imageUrl: 'https://loremflickr.com/200/200/telescope,space/all' },
  { word: 'אוהל', icon: Tent, label: 'Tent', imageUrl: 'https://loremflickr.com/200/200/tent,camping/all' },
  { word: 'מדחום', icon: Thermometer, label: 'Thermometer', imageUrl: 'https://loremflickr.com/200/200/thermometer,temp/all' },
  { word: 'כרטיס', icon: Ticket, label: 'Ticket', imageUrl: 'https://loremflickr.com/200/200/ticket,entry/all' },
  { word: 'פח', icon: Trash2, label: 'Trash', imageUrl: 'https://loremflickr.com/200/200/trash,bin/all' },
  { word: 'גביע', icon: Trophy, label: 'Trophy', imageUrl: 'https://loremflickr.com/200/200/trophy,gold/all' },
  { word: 'משאית', icon: Truck, label: 'Truck', imageUrl: 'https://loremflickr.com/200/200/truck,transport/all' },
  { word: 'טלוויזיה', icon: Tv, label: 'TV', imageUrl: 'https://loremflickr.com/200/200/television,tv/all' },
  { word: 'שרביט', icon: Wand2, label: 'Wand', imageUrl: 'https://loremflickr.com/200/200/wand,magic/all' },
  { word: 'יין', icon: Wine, label: 'Wine', imageUrl: 'https://loremflickr.com/200/200/wine,glass/all' },
];
